# Generated by Django 6.0.3 on 2026-04-03 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LekkiEnumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=200, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_floors', models.IntegerField(blank=True, null=True)),
                ('no_of_units', models.IntegerField(blank=True, null=True)),
                ('revenue_category', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_front', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo_gate', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo_signage', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo_street', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('completeness_status', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('area_in_me', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('full_plus_field', models.CharField(blank=True, db_column='full_plus_', max_length=50, null=True)),
                ('enumeration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed_house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_name_1', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name_2', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name_3', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name_4', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lekki_enumeration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('date_captured', models.DateTimeField(auto_now_add=True)),
                ('bill_image', models.ImageField(upload_to='bills/%Y/%m/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lekki_enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_distributions', to='core.lekkienumeration')),
            ],
            options={
                'db_table': 'bill_distribution_captures',
                'unique_together': {('lekki_enum', 'year')},
            },
        ),
    ]
