# Generated by Django 6.0.3 on 2026-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(help_text='e.g. 2', unique=True)),
                ('version_name', models.CharField(help_text='e.g. 1.0.1', max_length=50)),
                ('apk_file', models.FileField(upload_to='apks/')),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('is_forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_updates',
                'ordering': ['-version_code'],
            },
        ),
    ]
