# Generated by Django 6.0.3 on 2026-07-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propertycomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billdistribution',
            unique_together=set(),
        ),
    ]
