# Generated by Django 6.0.3 on 2026-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile_full_name_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_id', models.CharField(db_index=True, max_length=100)),
                ('merchant_reference', models.CharField(max_length=120, unique=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('payment_status', models.IntegerField(blank=True, null=True)),
                ('payment_description', models.CharField(blank=True, max_length=100)),
                ('raw_init_response', models.JSONField(blank=True, default=dict)),
                ('raw_status_response', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
