# Generated by Django 6.0.3 on 2026-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_routepaytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='property_manager',
            field=models.BooleanField(default=False),
        ),
    ]
