# Generated by Django 6.0.3 on 2026-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_userprofile_property_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepaytransaction',
            name='routepay_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
