# Generated by Django 6.0.3 on 2026-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_routepaytransaction_routepay_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepaytransaction',
            name='agency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='routepaytransaction',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='routepaytransaction',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='routepaytransaction',
            name='other_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='routepaytransaction',
            name='property_address',
            field=models.TextField(blank=True),
        ),
    ]
